[project]
name = "odoo-addons-sygel-technology-sy-account-invoicing"
version = "17.0.20241105.0"
dependencies = [
    "odoo-addon-bank_accounts_report>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
